### ISSUE TITLE
bug: When trying to build the android app, the last comand hangs forever

### ISSUE THREAD

**Issue by alexispurslane** [revoltchat/rvmob#18]
### What happened?

All the previous commands in the build instructions ran fine, but the final one, `yarn android`, just hangs forever after saying "Starting JS server..."

I thought this was going to build an APK I could use, do I need to visit a certain localhost address or something?

**Comment by Rexogamer** [comment]
This isn't a bug with the app itself. Try re-running the command as it might've gotten stuck somehow; if that doesn't work, you might need to start the JS server (Metro) separately (open a second terminal in the directory, run `yarn start`, then try re-running `yarn android` again). 

If this still fails, you might have some missing dependencies (i.e. Java/Android's build tools); however, if that turns out to be the issue, I might need to make the README clearer.

**Comment by alexispurslane** [comment]
I used netstat to figure out the port it was listening on and went to localhost:8081 in my browser. That gave me some broken options but no way to get an APK as far as I can tell. I tried using gradlew to build the app directly and it told me there were several dependencies I need to install, so I think that was it.

**Comment by Rexogamer** [comment]
Just to be clear, did you get it working in the end?

**Comment by alexispurslane** [comment]
> Just to be clear, did you get it working in the end?  

I had to go out and haven't had a chance since, but I think I'll be able to get it to work. You can close this issue for now if you want. Thank you!

**Comment by Rexogamer** [comment]
No worries; good luck! (Bear in mind that you can also get prebuilt debug builds from the Actions tab - the latest build can be downloaded [here](https://github.com/revoltchat/rvmob/suites/12402600558/artifacts/659472053).)
